#!/bin/bash

set -e

empty_arr=()

my_arr=(1 2 3 "banana" true)
echo "${my_arr[3]}" #? has to be enclosed in ${}

echo "$my_arr"      #? all elements in a single line
echo "${my_arr[@]}" #? use @ to print all elements in multiple line, ESSENTIAL FOR LOOPING

for element in "${my_arr[@]}"; do
    echo "$element"
done

my_arr+=("orange") #? add element, has to be enclosed in ()
unset my_arr[1]    #? remove element
echo "${my_arr[@]}"
