#!/usr/bin/env bash

# Iterate over a list of files and print their names
for file in *.txt; do
    echo $file
done

# Iterate over a list of numbers from 1 to 5
for i in {1..10}; do
    if [ $i -eq 5 ]; then #? will only print 1 through 4
        break
    fi
    echo $i
done

# Iterate over a string and print each character
#! very slow
for char in $( #! be careful as it counts the EOF as well
    grep -o "." <<<"Hello" #? same as `echo "Hello" | grep -o "."`
); do
    echo $char
done

# Iterate over a string and print each character
#! much faster
while IFS = read -r -n1 char; do
    echo "$char"
done <<<"Hello"

# a while loop that prints the numbers from 1 to 5:
count=1
while [ $count -le 5 ]; do
    echo $count
    count=$((count + 1))
done

# read input from a user until they enter a specific word, like "quit":

input=""
while [ "$input" != "quit" ]; do
    read -p "Enter a word (or 'quit' to exit): " input
    echo "You entered: $input"
    continue
done
